apiVersion: v1
kind: BuildConfig
metadata:
  name: tcskill.libertyapp
  labels:
    app: libertyapp
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/tcskill/libertyapp.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: libertyapp
        - name: BRANCH
          value: master
